version: "3"

x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
  volumes:
    - .:/app:cached
    - bundle:/usr/local/bundle
    - node_modules:/app/node_modules
    - packs:/app/public/packs
  environment:
    DB_HOST: db
    DB_USER: postgres
    DB_PASSWORD: password
    REDIS_HOST: redis
  depends_on:
    - db

services:
  db:
    image: postgres
    volumes:
      - datastore:/var/lib/postgresql/data
    expose:
      - "5432"
    environment:
      POSTGRES_PASSWORD: password
  web:
    <<: *app
    command: bash -c "rm -f /app/tmp/pids/server.pid && bin/setup && bundle exec rails server -p 3000 -b '0.0.0.0'"
    ports:
      - "${PORT:-3000}:3000"

  #sidekiq:
  #  <<: *app
  #  command: "bundle exec sidekiq"
  #  depends_on:
  #    - web
  #    - redis
  #  tty: false
  #  stdin_open: false
  #redis:
  #  image: redis:latest
  #  expose:
  #    - "6379"

volumes:
  datastore: {}
  bundle:
    driver: local
  node_modules:
  packs:
